import { z } from 'zod';
import archiver from 'archiver';
import { authenticate } from '../../middlewares/authenticate.js';
import { projectService } from '../../services/project.service.js';
import { redis } from '../../lib/redis.js';

const createProjectBody = z.object({ idea_input: z.string().min(5).max(2000) });

// artifact filename → ZIP 내 경로 매핑
const ZIP_PATH_MAP = {
  // docs (기획/설계)
  'idea_analysis_report.md': 'docs/01-idea-analysis.md',
  'product_requirements.md': 'docs/02-requirements.md',
  'design_system.md':        'docs/03-design-system.md',
  'wireframes.md':           'docs/03-wireframes.md',
  'components.md':           'docs/03-components.md',
  'tech_stack.md':           'docs/04-tech-stack.md',
  'architecture.md':         'docs/04-architecture.md',
  'database_schema.md':      'docs/04-database-schema.md',
  'project_structure.md':    'docs/04-project-structure.md',
  // frontend
  'frontend_setup.md':       'frontend/SETUP.md',
  'frontend_components.md':  'frontend/COMPONENTS.md',
  'frontend_pages.md':       'frontend/PAGES.md',
  'frontend_hooks.md':       'frontend/HOOKS.md',
  // backend
  'backend_setup.md':        'backend/SETUP.md',
  'backend_schema.md':       'backend/SCHEMA.md',
  'backend_routes.md':       'backend/ROUTES.md',
  'backend_services.md':     'backend/SERVICES.md',
  // tests
  'test_strategy.md':        'tests/STRATEGY.md',
  'backend_tests.md':        'tests/BACKEND.md',
  'frontend_tests.md':       'tests/FRONTEND.md',
  'e2e_tests.md':            'tests/E2E.md',
  'code_review.md':          'tests/CODE-REVIEW.md',
  // deploy
  'docker.md':               'deploy/DOCKER.md',
  'cicd.md':                 'deploy/CICD.md',
  'infrastructure.md':       'deploy/INFRASTRUCTURE.md',
  'monitoring.md':           'deploy/MONITORING.md',
  // 최종 보고서 → 루트 README
  'final_report.md':         'README.md',
};

function toSlug(title) {
  return title
    .replace(/[^\w\s가-힣]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 40) || 'project';
}

function buildIndexMd(title, ideaInput, artifacts) {
  const exists = new Set(artifacts.map((a) => a.filename));
  const section = (label, files) => {
    const items = files
      .filter(([src]) => exists.has(src))
      .map(([src, dest]) => `- [\`${dest}\`](./${dest})`)
      .join('\n');
    return items ? `### ${label}\n${items}` : '';
  };

  return [
    `# ${title}`,
    '',
    `> ${ideaInput}`,
    '',
    '## 프로젝트 구조',
    '',
    section('기획 / 설계 문서', [
      ['idea_analysis_report.md', 'docs/01-idea-analysis.md'],
      ['product_requirements.md', 'docs/02-requirements.md'],
      ['design_system.md',        'docs/03-design-system.md'],
      ['wireframes.md',           'docs/03-wireframes.md'],
      ['components.md',           'docs/03-components.md'],
      ['tech_stack.md',           'docs/04-tech-stack.md'],
      ['architecture.md',         'docs/04-architecture.md'],
      ['database_schema.md',      'docs/04-database-schema.md'],
      ['project_structure.md',    'docs/04-project-structure.md'],
    ]),
    '',
    section('프론트엔드', [
      ['frontend_setup.md',      'frontend/SETUP.md'],
      ['frontend_components.md', 'frontend/COMPONENTS.md'],
      ['frontend_pages.md',      'frontend/PAGES.md'],
      ['frontend_hooks.md',      'frontend/HOOKS.md'],
    ]),
    '',
    section('백엔드', [
      ['backend_setup.md',    'backend/SETUP.md'],
      ['backend_schema.md',   'backend/SCHEMA.md'],
      ['backend_routes.md',   'backend/ROUTES.md'],
      ['backend_services.md', 'backend/SERVICES.md'],
    ]),
    '',
    section('테스트', [
      ['test_strategy.md',   'tests/STRATEGY.md'],
      ['backend_tests.md',   'tests/BACKEND.md'],
      ['frontend_tests.md',  'tests/FRONTEND.md'],
      ['e2e_tests.md',       'tests/E2E.md'],
      ['code_review.md',     'tests/CODE-REVIEW.md'],
    ]),
    '',
    section('배포 / 인프라', [
      ['docker.md',         'deploy/DOCKER.md'],
      ['cicd.md',           'deploy/CICD.md'],
      ['infrastructure.md', 'deploy/INFRASTRUCTURE.md'],
      ['monitoring.md',     'deploy/MONITORING.md'],
    ]),
    '',
    `---`,
    `*Generated by AgileFlow*`,
  ].filter((l) => l !== null).join('\n');
}

const tags = ['Projects'];
const security = [{ cookieAuth: [] }];

const projectSchema = {
  type: 'object',
  properties: {
    id: { type: 'string', format: 'uuid' },
    title: { type: 'string' },
    ideaInput: { type: 'string' },
    status: { type: 'string', enum: ['pending', 'running', 'completed', 'failed'] },
    currentStep: { type: 'integer' },
    createdAt: { type: 'string', format: 'date-time' },
    completedAt: { type: 'string', nullable: true },
  },
};

export async function projectRoutes(app) {
  app.post('/', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '프로젝트 생성 + 파이프라인 실행',
      security,
      body: {
        type: 'object',
        required: ['idea_input'],
        properties: {
          idea_input: { type: 'string', minLength: 5, maxLength: 2000, description: '아이디어 설명' },
        },
      },
      response: {
        201: {
          description: '생성된 프로젝트',
          type: 'object',
          properties: { data: projectSchema },
        },
      },
    },
  }, async (req, reply) => {
    const { idea_input } = createProjectBody.parse(req.body);
    const project = await projectService.create({ userId: req.user.id, ideaInput: idea_input });
    return reply.code(201).send({ data: project });
  });

  app.get('/', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '내 프로젝트 목록',
      security,
      response: {
        200: {
          type: 'object',
          properties: { data: { type: 'array', items: projectSchema } },
        },
      },
    },
  }, async (req, reply) => {
    const projects = await projectService.listByUser(req.user.id);
    return { data: projects };
  });

  app.get('/:id', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '프로젝트 상세 조회',
      security,
      params: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } },
      response: {
        200: { type: 'object', properties: { data: projectSchema } },
      },
    },
  }, async (req, reply) => {
    const project = await projectService.getById(req.params.id, req.user.id);
    return { data: project };
  });

  app.get('/:id/artifacts', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '파이프라인 산출물 목록',
      security,
      params: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } },
      response: {
        200: {
          type: 'object',
          properties: {
            data: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: { type: 'string' },
                  agentName: { type: 'string' },
                  filename: { type: 'string' },
                  content: { type: 'string' },
                  status: { type: 'string' },
                },
              },
            },
          },
        },
      },
    },
  }, async (req, reply) => {
    const artifacts = await projectService.getArtifacts(req.params.id, req.user.id);
    return { data: artifacts };
  });

  app.get('/:id/agent-statuses', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '에이전트별 최신 실행 상태',
      security,
      params: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } },
      response: {
        200: { type: 'object', properties: { data: { type: 'object', additionalProperties: { type: 'string' } } } },
      },
    },
  }, async (req, reply) => {
    const statuses = await projectService.getAgentStatuses(req.params.id, req.user.id);
    return { data: statuses };
  });

  app.get('/:id/stream', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '파이프라인 실시간 이벤트 스트림 (SSE)',
      security,
      params: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } },
      produces: ['text/event-stream'],
      response: { 200: { type: 'string', description: 'Server-Sent Events 스트림' } },
    },
  }, async (req, reply) => {
    const { id } = req.params;
    reply.raw.setHeader('Content-Type', 'text/event-stream');
    reply.raw.setHeader('Cache-Control', 'no-cache');
    reply.raw.setHeader('Connection', 'keep-alive');
    reply.raw.flushHeaders();

    const statuses = await projectService.getAgentStatuses(id, req.user.id);
    for (const [agent, status] of Object.entries(statuses)) {
      reply.raw.write(`data: ${JSON.stringify({ agent, status })}\n\n`);
    }

    const subscriber = redis.duplicate();
    await subscriber.subscribe(`project:${id}:events`);

    subscriber.on('message', (_ch, message) => {
      reply.raw.write(`data: ${message}\n\n`);
    });

    req.raw.on('close', () => {
      subscriber.unsubscribe();
      subscriber.disconnect();
    });
  });

  app.patch('/:id/artifacts/:artifactId', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '산출물 내용 수정',
      security,
      params: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          artifactId: { type: 'string', format: 'uuid' },
        },
      },
      body: {
        type: 'object',
        required: ['content'],
        properties: { content: { type: 'string' } },
      },
      response: {
        200: {
          type: 'object',
          properties: {
            data: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                filename: { type: 'string' },
                content: { type: 'string' },
              },
            },
          },
        },
      },
    },
  }, async (req, reply) => {
    const artifact = await projectService.updateArtifact(
      req.params.id,
      req.params.artifactId,
      req.body.content,
      req.user.id,
    );
    return { data: artifact };
  });

  app.post('/:id/steps/:step/skip', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '파이프라인 스텝 건너뛰기',
      security,
      params: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          step: { type: 'integer', minimum: 1, maximum: 7 },
        },
      },
      response: {
        200: {
          type: 'object',
          properties: {
            data: {
              type: 'object',
              properties: {
                projectId: { type: 'string' },
                step: { type: 'integer' },
                skipped: { type: 'boolean' },
              },
            },
          },
        },
      },
    },
  }, async (req, reply) => {
    const result = await projectService.skipStep(
      req.params.id,
      Number(req.params.step),
      req.user.id,
    );
    return { data: result };
  });

  app.get('/:id/download', {
    preHandler: authenticate,
    schema: {
      tags,
      summary: '산출물 ZIP 다운로드',
      security,
      params: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } },
    },
  }, async (req, reply) => {
    const [project, artifacts] = await Promise.all([
      projectService.getById(req.params.id, req.user.id),
      projectService.getArtifacts(req.params.id, req.user.id),
    ]);

    const slug = toSlug(project.title);

    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.append(
      buildIndexMd(project.title, project.ideaInput, artifacts),
      { name: `${slug}/INDEX.md` },
    );

    for (const a of artifacts) {
      const zipPath = ZIP_PATH_MAP[a.filename] ?? `misc/${a.filename}`;
      archive.append(a.content ?? '', { name: `${slug}/${zipPath}` });
    }

    archive.finalize();

    return reply
      .header('Content-Type', 'application/zip')
      .header('Content-Disposition', `attachment; filename="${slug}.zip"`)
      .send(archive);
  });
}
